In [0]:
a = 5
b = 10
c = 5+10
print(c)

15


In [0]:
d = a+b
d

15

In [0]:
a = 7
b = 5
c = 12
if(a>b):
  print( a)
else:
  print(b )

7


In [0]:
a = [3,5,7,9]
a.reverse()
print(a)

[9, 7, 5, 3]


In [0]:
a = [1,1,2,3,5,3]
sum = 0
for i in a:
  sum = sum+i
  print(sum)

1
2
4
7
12
15


In [0]:
total = 0
n = 0
list1 = [11, 5, 17, 18, 23] 
while (n < len(list1)):
  total = total+list1(n)
  n +=1
print(total)


TypeError: ignored

In [0]:
import numpy as np
arr = np.array([[1,2,3],[4,2,5]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [0]:
def fibonacci(n): 
    a = 0
    b = 1
    if n < 0: 
        print("Incorrect input") 
    elif n == 0: 
        return a 
    elif n == 1: 
        return b 
    else: 
        for i in range(2,n+1): 
            c = a + b 
            a = b 
            b = c 
        return b  
  
print(fibonacci(9)) 

None


In [0]:
a = 0
b = 1
print(a)
print(b)
n = 7
for i in range(1,n): 
            c = a + b 
            a = b 
            b = c 
print(c)


0
1
13


In [0]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [0]:
vector_row

array([1, 2, 3])

In [0]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [0]:
vector_column

array([[1],
       [2],
       [3]])

In [0]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [0]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [0]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [0]:
a = np.random.random((3,3))
a

array([[0.41637769, 0.99946266, 0.58517121],
       [0.61551333, 0.82622185, 0.68148103],
       [0.75339732, 0.52605346, 0.83468727]])

In [0]:
b = np.random.random((3,3))
b

array([[0.31276556, 0.41363601, 0.07355488],
       [0.57352712, 0.38539898, 0.86431898],
       [0.38309113, 0.01682569, 0.35769422]])

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])

In [0]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
x = np.random.rand(3,3)

In [0]:
x

array([[0.58433837, 0.57732775, 0.44401815],
       [0.60858467, 0.78693385, 0.42158782],
       [0.94502402, 0.47822441, 0.06809847]])

In [0]:
y = np.random.rand(3,3)
y

array([[0.52740752, 0.87880354, 0.49520842],
       [0.39879134, 0.17488027, 0.55097685],
       [0.5955454 , 0.26631848, 0.30591262]])

In [0]:
np.cross(x,y) #cross product

array([[-0.10430716, -0.05519077,  0.20903163],
       [ 0.35985495, -0.16719049, -0.20739296],
       [ 0.128159  , -0.24853905, -0.03312699]])

In [0]:
np.dot(x,y) # dot product x.dot(y)

array([[0.80285072, 0.7327321 , 0.74329427],
       [0.88586922, 0.78472219, 0.86392763],
       [0.72968026, 0.93225834, 0.75230661]])

In [0]:
np.add(x,y) # addition of two vectors

array([[1.11174589, 1.45613129, 0.93922658],
       [1.007376  , 0.96181412, 0.97256467],
       [1.54056941, 0.74454289, 0.3740111 ]])

In [0]:
X = np.random.randint(9, size=(3,3))

In [0]:
X

array([[8, 0, 0],
       [3, 5, 0],
       [3, 4, 0]])

In [0]:
Y = np.random.randint(9, size=(3,3))
Y

array([[1, 6, 3],
       [8, 1, 8],
       [5, 5, 7]])

In [0]:
np.cross(X,Y)

array([[  0, -24,  48],
       [ 40, -24, -37],
       [ 28, -21,  -5]])

In [0]:
np.dot(X,Y)

array([[ 8, 48, 24],
       [43, 23, 49],
       [35, 22, 41]])

In [0]:
np.add(X,Y)

array([[ 9,  6,  3],
       [11,  6,  8],
       [ 8,  9,  7]])

In [0]:
import pandas as pd
data = pd.read_csv("iris.csv")

In [0]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [0]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
data.isnull()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
5           False        False         False        False    False
6           False        False         False        False    False
7           False        False         False        False    False
8           False        False         False        False    False
9           False        False         False        False    False
10          False        False         False        False    False
11          False        False         False        False    False
12          False        False         False        False    False
13          False        False         False        False    False
14          False        False         False        False    False
15          False        False         False        False    False
16          False        False         False        False    False
17          False        False         False        False    False
18          False        False         False        False    False
19          False        False         False        False    False
20          False        False         False        False    False
21          False        False         False        False    False
22          False        False         False        False    False
23          False        False         False        False    False
24          False        False         False        False    False
25          False        False         False        False    False
26          False        False         False        False    False
27          False        False         False        False    False
28          False        False         False        False    False
29          False        False         False        False    False
..            ...          ...           ...          ...      ...
120         False        False         False        False    False
121         False        False         False        False    False
122         False        False         False        False    False
123         False        False         False        False    False
124         False        False         False        False    False
125         False        False         False        False    False
126         False        False         False        False    False
127         False        False         False        False    False
128         False        False         False        False    False
129         False        False         False        False    False
130         False        False         False        False    False
131         False        False         False        False    False
132         False        False         False        False    False
133         False        False         False        False    False
134         False        False         False        False    False
135         False        False         False        False    False
136         False        False         False        False    False
137         False        False         False        False    False
138         False        False         False        False    False
139         False        False         False        False    False
140         False        False         False        False    False
141         False        False         False        False    False
142         False        False         False        False    False
143         False        False         False        False    False
144         False        False         False        False    False
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        

In [0]:
data.isna()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
5           False        False         False        False    False
6           False        False         False        False    False
7           False        False         False        False    False
8           False        False         False        False    False
9           False        False         False        False    False
10          False        False         False        False    False
11          False        False         False        False    False
12          False        False         False        False    False
13          False        False         False        False    False
14          False        False         False        False    False
15          False        False         False        False    False
16          False        False         False        False    False
17          False        False         False        False    False
18          False        False         False        False    False
19          False        False         False        False    False
20          False        False         False        False    False
21          False        False         False        False    False
22          False        False         False        False    False
23          False        False         False        False    False
24          False        False         False        False    False
25          False        False         False        False    False
26          False        False         False        False    False
27          False        False         False        False    False
28          False        False         False        False    False
29          False        False         False        False    False
..            ...          ...           ...          ...      ...
120         False        False         False        False    False
121         False        False         False        False    False
122         False        False         False        False    False
123         False        False         False        False    False
124         False        False         False        False    False
125         False        False         False        False    False
126         False        False         False        False    False
127         False        False         False        False    False
128         False        False         False        False    False
129         False        False         False        False    False
130         False        False         False        False    False
131         False        False         False        False    False
132         False        False         False        False    False
133         False        False         False        False    False
134         False        False         False        False    False
135         False        False         False        False    False
136         False        False         False        False    False
137         False        False         False        False    False
138         False        False         False        False    False
139         False        False         False        False    False
140         False        False         False        False    False
141         False        False         False        False    False
142         False        False         False        False    False
143         False        False         False        False    False
144         False        False         False        False    False
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        

In [0]:
 pd.isna(data)

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
5           False        False         False        False    False
6           False        False         False        False    False
7           False        False         False        False    False
8           False        False         False        False    False
9           False        False         False        False    False
10          False        False         False        False    False
11          False        False         False        False    False
12          False        False         False        False    False
13          False        False         False        False    False
14          False        False         False        False    False
15          False        False         False        False    False
16          False        False         False        False    False
17          False        False         False        False    False
18          False        False         False        False    False
19          False        False         False        False    False
20          False        False         False        False    False
21          False        False         False        False    False
22          False        False         False        False    False
23          False        False         False        False    False
24          False        False         False        False    False
25          False        False         False        False    False
26          False        False         False        False    False
27          False        False         False        False    False
28          False        False         False        False    False
29          False        False         False        False    False
..            ...          ...           ...          ...      ...
120         False        False         False        False    False
121         False        False         False        False    False
122         False        False         False        False    False
123         False        False         False        False    False
124         False        False         False        False    False
125         False        False         False        False    False
126         False        False         False        False    False
127         False        False         False        False    False
128         False        False         False        False    False
129         False        False         False        False    False
130         False        False         False        False    False
131         False        False         False        False    False
132         False        False         False        False    False
133         False        False         False        False    False
134         False        False         False        False    False
135         False        False         False        False    False
136         False        False         False        False    False
137         False        False         False        False    False
138         False        False         False        False    False
139         False        False         False        False    False
140         False        False         False        False    False
141         False        False         False        False    False
142         False        False         False        False    False
143         False        False         False        False    False
144         False        False         False        False    False
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        

In [93]:
 df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, 3, np.nan, 4]],
                   columns=list('ABCD'))
df

A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4

In [94]:
df.fillna(0)

A    B    C  D
0  0.0  2.0  0.0  0
1  3.0  4.0  0.0  1
2  0.0  0.0  0.0  5
3  0.0  3.0  0.0  4

In [0]:
values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}

In [96]:
df.fillna(value=values)

A    B    C  D
0  0.0  2.0  2.0  0
1  3.0  4.0  2.0  1
2  0.0  1.0  2.0  5
3  0.0  3.0  2.0  4

In [0]:
 df1 = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, 3, np.nan, 4]],
                   columns=list('ABCD'))

In [98]:
df1

A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4

In [0]:
from numpy import nan as NA
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])

In [106]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [0]:
cleaned = data.dropna()

In [108]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [110]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [111]:
# iloc
df = pd.DataFrame(np.random.randn(7, 3))
df

0         1         2
0  0.576827 -0.907166  0.493469
1 -0.075788 -1.180847  0.790487
2  0.580389 -1.343218  0.396053
3  0.973366  0.938103  0.374458
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [0]:
df.iloc[:4, 1] = NA

In [113]:
df

0         1         2
0  0.576827       NaN  0.493469
1 -0.075788       NaN  0.790487
2  0.580389       NaN  0.396053
3  0.973366       NaN  0.374458
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [0]:
df.iloc[:2, 2] = NA

In [115]:
df

0         1         2
0  0.576827       NaN       NaN
1 -0.075788       NaN       NaN
2  0.580389       NaN  0.396053
3  0.973366       NaN  0.374458
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [117]:
df.dropna()

0         1         2
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [119]:
df.fillna(0)

0         1         2
0  0.576827  0.000000  0.000000
1 -0.075788  0.000000  0.000000
2  0.580389  0.000000  0.396053
3  0.973366  0.000000  0.374458
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [120]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.576827  0.500000  0.000000
1 -0.075788  0.500000  0.000000
2  0.580389  0.500000  0.396053
3  0.973366  0.500000  0.374458
4  0.925904 -0.937366 -1.287146
5  3.149735  0.282706 -0.673352
6 -0.528890  0.131026 -0.790756

In [123]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [0]:
data2 = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [125]:
data2

a  1    0.577001
   2    0.693654
   3    1.598193
b  1   -0.250101
   3   -1.511029
c  1   -0.221438
   2    0.240530
d  2    0.654440
   3   -0.990117
dtype: float64

In [0]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [128]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
# indexing using loc and iloc gets rows (or columns) with particular labels from the index. 
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [130]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [131]:
data.iloc[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [132]:
data.loc[:'Utah', 'two'] #Selects single column or subset of columns by label

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [136]:
data.loc[:'New York', 'four'] #  gets rows (or columns) at particular positions in the index (so it only takes integers).

Ohio         3
Colorado     7
Utah        11
New York    15
Name: four, dtype: int64

In [0]:
one = pd.DataFrame({
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5'],
   'Marks_scored':[98,90,87,69,78]},
   index=[1,2,3,4,5])

In [138]:
one

Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78

In [0]:
two = pd.DataFrame({
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5'],
   'Marks_scored':[89,80,79,97,88]},
   index=[1,2,3,4,5])

In [140]:
two

Name subject_id  Marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88

In [141]:
print (pd.concat([one,two]))

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88


In [142]:
print (pd.concat([one,two],keys=['x','y']))

       Name subject_id  Marks_scored
x 1    Alex       sub1            98
  2     Amy       sub2            90
  3   Allen       sub4            87
  4   Alice       sub6            69
  5  Ayoung       sub5            78
y 1   Billy       sub2            89
  2   Brian       sub4            80
  3    Bran       sub3            79
  4   Bryce       sub6            97
  5   Betty       sub5            88


In [0]:
# The index of the resultant is duplicated; each index is repeated. If the resultant object has to follow its own indexing, set ignore_index to True.

In [144]:
print (pd.concat([one,two],keys=['x','y'],ignore_index=True))

     Name subject_id  Marks_scored
0    Alex       sub1            98
1     Amy       sub2            90
2   Allen       sub4            87
3   Alice       sub6            69
4  Ayoung       sub5            78
5   Billy       sub2            89
6   Brian       sub4            80
7    Bran       sub3            79
8   Bryce       sub6            97
9   Betty       sub5            88


In [145]:
#If two objects need to be added along axis=1, then the new columns will be appended.
print (pd.concat([one,two],axis=1)) 

     Name subject_id  Marks_scored   Name subject_id  Marks_scored
1    Alex       sub1            98  Billy       sub2            89
2     Amy       sub2            90  Brian       sub4            80
3   Allen       sub4            87   Bran       sub3            79
4   Alice       sub6            69  Bryce       sub6            97
5  Ayoung       sub5            78  Betty       sub5            88
